// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | "/background.js"
    | "/content-scripts/content.js"
    | "/icon/128.png"
    | "/icon/16.png"
    | "/icon/32.png"
    | "/icon/36.png"
    | "/icon/48.png"
    | "/icon/96.png"
    | "/imgs/background-select.png"
    | "/imgs/bookmark.jpg"
    | "/imgs/preview.png"
    | "/imgs/step-1.jpg"
    | "/imgs/step-2.jpg"
    | "/logo.png"
    | "/newtab.html"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime extends Runtime.Static {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
